---
openapi: 3.0.3
info:
  title: Get information about a Public IP
  version: 1.0.0
  description: From a simple public IP you can get geographical information such as the City and Country
security:
  - BasicAuth: []
servers:
  - url: https://api.gcp.cointet.com
    description: Production server (uses live data)
paths:
  /locate/{ip}:
    get:
      summary: Locate an IP
      description: |
        Upon successful execution, returns a all known information about a public IP. 
        The API will also give a photo to illustrate the nearest city found.
      parameters:
        - in: path
          name: ip
          description: Public IP to locate
          required: true
          schema:
            $ref: '#/components/schemas/ip_param'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locate'
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locate'
  /details/{countryCode}:
    get:
      summary: Get Country Details from a Country Code
      description: |
        Useful to check if a country exists, and get some details about it
      parameters:
        - in: path
          name: countryCode
          description: The Country Code
          required: true
          schema:
            $ref: '#/components/schemas/countryCode_param'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /chatgpt/{city}:
    get:
      summary: Get an AI generated sentence about the city
      description: |
        One short sentence to describe the city requested
      parameters:
        - in: path
          name: city
          description: The City Name
          required: true
          schema:
            $ref: '#/components/schemas/city_param'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chatgpt'
        "500":
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    error:
      type: object
      properties:
        message:
          type: string
          example: "Error with your parameters"
    locate:
      type: object
      properties:
        country:
          type: string
          example: "United States"
        countryCode:
          type: string
          example: "US"
        regionName:
          type: string
          example: "Florida"
        city:
          type: string
          example: "Miami"
        ip:
          type: string
          example: "173.255.189.42"
        photo:
          type: string
          example: "https://shorturl.at/eyMV7"
    details:
      type: object
      properties:
        country:
          type: string
          example: "France"
        country_name:
          type: string
          example: "France"
        code:
          type: string
          example: "FR"
        details:
          type: string
          example: "A great country in europe"
    chatgpt:
      type: object
      properties:
        id:
          type: string
          example: "chatcmpl-7MyOB5F7foDg3ELbxqjgpOQJm4QWT"
        model:
          type: string
          example: "gpt-3.5-turbo-0301"
        answer:
            type: string
            example: "Versailles is a city located in the Île-de-France region of France, known for its magnificent Palace of Versailles."
        question:
            type: string
            example: "In one sentence, give me some information about the city: Versailles"
    city_param:
      type: string
      example: "Marbella"
    countryCode_param:
      type: string
      example: "ES"
    ip_param:
      type: string
      example: "46.8.173.77"
