---
openapi: 3.0.3
info:
  title: Get information about a Public IP
  version: 1.0.0
  description: From a simple public IP you can get geographical information such as the City and Country
security:
  - BasicAuth: []
servers:
  - url: https://api.gcp.cointet.com
    description: Production server (uses live data)
paths:
  /locate:
    get:
      summary: Locate an IP
      description: |
        Upon successful execution, returns a all known information about a public IP. 
        The API will also give a photo to illustrate the nearest city found.
      parameters:
        - in: query
          name: ip
          description: Public IP to locate
          schema:
            $ref: '#/components/schemas/ip'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locate'
        "500":
          description: ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locate'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    locate:
      type: object
      properties:
        country:
          type: string
          example: "Spain"
        regionName:
          type: string
          example: "Andalusia"
        city:
          type: string
          example: "Marbella"
        ip:
          type: string
          example: "78.80.98.56"
        photo:
          type: string
          example: "https://google.com/image"
    ip:
      type: string
